---
title: "Untitled"
format: html
editor: visual
---

# Yield model

```{r}
reg_mod <- lmer(yield_adj_to_13_5_percent ~ cultivar + pgr_trt_name + 
                (1 | year) + (1 | location), 
                data = data %>% mutate(pgr_trt_name = fct_relevel(pgr_trt_name, "No_PGR"),
                                       cultivar = fct_relevel(cultivar, "Esma")))

data_clean <- data %>%
  filter(!is.na(cultivar), !is.na(pgr_trt_name), !is.na(year), !is.na(location))

# Predict using the cleaned dataset
data_pred <- data_clean %>%
  mutate(predicted_yield = predict(reg_mod, newdata = data_clean, re.form = NULL))

# Check result
data_pred

```

# Plant height model

```{r}
reg_mod_height <- lmer(avg_height_at_phys_maturity ~ cultivar + pgr_trt_name + 
                (1 | year) + (1 | location), 
                data = data %>% mutate(pgr_trt_name = fct_relevel(pgr_trt_name, "No_PGR"),
                                       cultivar = fct_relevel(cultivar, "Esma")))

# Predict using the cleaned dataset
data_pred_height <- data_pred %>%
  mutate(predicted_height = predict(reg_mod_height, newdata = data_pred, re.form = NULL))

# Check result
data_pred_height
```

# Lodging model

```{r}
reg_mod_lodging <- lmer(lodging_index_2 ~ cultivar + pgr_trt_name + 
                (1 | year) + (1 | location), 
                data = data %>% mutate(pgr_trt_name = fct_relevel(pgr_trt_name, "No_PGR"),
                                       cultivar = fct_relevel(cultivar, "Esma")))

# Predict using the cleaned dataset
data_pred_lodging <- data_pred_height %>%
  mutate(predicted_lodging = predict(reg_mod_lodging, newdata = data_pred_height, re.form = NULL))

# Check result
data_pred_lodging
```

# protein model

```{r}
reg_mod_protein <- lmer(protein_percent_dm ~ cultivar + pgr_trt_name + 
                (1 | year) + (1 | location), 
                data = data %>% mutate(pgr_trt_name = fct_relevel(pgr_trt_name, "No_PGR"),
                                       cultivar = fct_relevel(cultivar, "Esma")))

# Predict using the cleaned dataset
data_pred_protein <- data_pred_lodging %>%
  mutate(predicted_protein = predict(reg_mod_protein, newdata = data_pred_lodging, re.form = NULL))

# Check result
data_pred_protein
```
